spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travelX?createDatabaseIfNotExist=true
    username: root
    password:
  devtools:
    livereload:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

    servlet:
      multipart:
        enabled: true
        file-size-threshold: 2MB
        max-file-size: 5MB
        max-request-size: 10MB

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  bucket:
    name: coderstravelx

cloud:
  aws:
    credentials:
      access-key: AKIAXKTGPKP3TUHMLWWT
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false







